- name: Copy the service account files
  copy:
    src: "{{ svc_account_csr }}"
    dest: "{{ svc_account_dir }}/"

- name: Create the service account certificate and private key
  shell: >
    cfssl gencert
    -ca="{{ certificate_authority }}"
    -ca-key="{{ certificate_authority_key }}"
    -config="{{ certificate_authority_config }}"
    -profile=kubernetes
    "{{ svc_account_csr }}" | cfssljson -bare service-account
  args:
    chdir: "{{ svc_account_dir }}"